name: C/C++ CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install -y clang

    - name: Configure Compiler
      run: |
        echo "CC=/usr/bin/clang" >> $GITHUB_ENV
        echo "CXX=/usr/bin/clang++" >> $GITHUB_ENV

    - name: Create Build Directory
      run: mkdir build

    - name: Configure CMake
      run: cmake -B build

    - name: Build
      run: cmake --build build -j

    - name: Test
      run: |
        cp -r data/ build/
        ctest --test-dir build --verbose
        rm -rf build/data/
    