name: C/C++ CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  Clang-AOT-Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install -y clang

    - name: Configure Compiler
      run: |
        echo "CC=/usr/bin/clang" >> $GITHUB_ENV
        echo "CXX=/usr/bin/clang++" >> $GITHUB_ENV

    - name: Create Build Directory
      run: mkdir build

    - name: Configure CMake
      run: cmake -B build

    - name: Build
      run: cmake --build build -j

    - name: Test
      run: |
        cp -r data/ build/
        ctest --test-dir build --verbose
        rm -rf build/data/

  GCC-AOT-Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install -y g++

    - name: Configure Compiler
      run: |
        echo "CC=/usr/bin/gcc" >> $GITHUB_ENV
        echo "CXX=/usr/bin/g++" >> $GITHUB_ENV

    - name: Create Build Directory
      run: mkdir build

    - name: Configure CMake
      run: cmake -B build

    - name: Build
      run: cmake --build build -j

    - name: Test
      run: |
        cp -r data/ build/
        ctest --test-dir build --verbose
        rm -rf build/data/

  JIT-Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install -y clang llvm python3

    - name: Compile ByteCode
      run: python3 jit/compile_bc.py

    - name: Test
      run: python3 jit/run_bc.py
    